//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("mdlGSB", "rapport_fk2", "MEDECIN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PPE3GSB.MEDECIN), "RAPPORT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PPE3GSB.RAPPORT), true)]
[assembly: EdmRelationshipAttribute("mdlGSB", "rapport_fk1", "Visiteur", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PPE3GSB.Visiteur), "RAPPORT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PPE3GSB.RAPPORT), true)]

#endregion

namespace PPE3GSB
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class connectGSB : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet connectGSB à l'aide de la chaîne de connexion trouvée dans la section 'connectGSB' du fichier de configuration d'application.
        /// </summary>
        public connectGSB() : base("name=connectGSB", "connectGSB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet connectGSB.
        /// </summary>
        public connectGSB(string connectionString) : base(connectionString, "connectGSB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet connectGSB.
        /// </summary>
        public connectGSB(EntityConnection connection) : base(connection, "connectGSB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<MEDECIN> MEDECIN
        {
            get
            {
                if ((_MEDECIN == null))
                {
                    _MEDECIN = base.CreateObjectSet<MEDECIN>("MEDECIN");
                }
                return _MEDECIN;
            }
        }
        private ObjectSet<MEDECIN> _MEDECIN;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<MEDICAMENT> MEDICAMENT
        {
            get
            {
                if ((_MEDICAMENT == null))
                {
                    _MEDICAMENT = base.CreateObjectSet<MEDICAMENT>("MEDICAMENT");
                }
                return _MEDICAMENT;
            }
        }
        private ObjectSet<MEDICAMENT> _MEDICAMENT;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<RAPPORT> RAPPORT
        {
            get
            {
                if ((_RAPPORT == null))
                {
                    _RAPPORT = base.CreateObjectSet<RAPPORT>("RAPPORT");
                }
                return _RAPPORT;
            }
        }
        private ObjectSet<RAPPORT> _RAPPORT;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Visiteur> Visiteur
        {
            get
            {
                if ((_Visiteur == null))
                {
                    _Visiteur = base.CreateObjectSet<Visiteur>("Visiteur");
                }
                return _Visiteur;
            }
        }
        private ObjectSet<Visiteur> _Visiteur;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet MEDECIN. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMEDECIN(MEDECIN mEDECIN)
        {
            base.AddObject("MEDECIN", mEDECIN);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet MEDICAMENT. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMEDICAMENT(MEDICAMENT mEDICAMENT)
        {
            base.AddObject("MEDICAMENT", mEDICAMENT);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet RAPPORT. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToRAPPORT(RAPPORT rAPPORT)
        {
            base.AddObject("RAPPORT", rAPPORT);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Visiteur. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVisiteur(Visiteur visiteur)
        {
            base.AddObject("Visiteur", visiteur);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdlGSB", Name="MEDECIN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MEDECIN : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet MEDECIN.
        /// </summary>
        /// <param name="idMedecin">Valeur initiale de la propriété idMedecin.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété prenom.</param>
        /// <param name="adresse">Valeur initiale de la propriété adresse.</param>
        /// <param name="departement">Valeur initiale de la propriété departement.</param>
        public static MEDECIN CreateMEDECIN(global::System.Int32 idMedecin, global::System.String nom, global::System.String prenom, global::System.String adresse, global::System.Int32 departement)
        {
            MEDECIN mEDECIN = new MEDECIN();
            mEDECIN.idMedecin = idMedecin;
            mEDECIN.nom = nom;
            mEDECIN.prenom = prenom;
            mEDECIN.adresse = adresse;
            mEDECIN.departement = departement;
            return mEDECIN;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMedecin
        {
            get
            {
                return _idMedecin;
            }
            set
            {
                if (_idMedecin != value)
                {
                    OnidMedecinChanging(value);
                    ReportPropertyChanging("idMedecin");
                    _idMedecin = StructuralObject.SetValidValue(value, "idMedecin");
                    ReportPropertyChanged("idMedecin");
                    OnidMedecinChanged();
                }
            }
        }
        private global::System.Int32 _idMedecin;
        partial void OnidMedecinChanging(global::System.Int32 value);
        partial void OnidMedecinChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false, "nom");
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, false, "prenom");
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, false, "adresse");
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value, true, "tel");
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private global::System.String _tel;
        partial void OntelChanging(global::System.String value);
        partial void OntelChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idSpecialite
        {
            get
            {
                return _idSpecialite;
            }
            set
            {
                OnidSpecialiteChanging(value);
                ReportPropertyChanging("idSpecialite");
                _idSpecialite = StructuralObject.SetValidValue(value, true, "idSpecialite");
                ReportPropertyChanged("idSpecialite");
                OnidSpecialiteChanged();
            }
        }
        private global::System.String _idSpecialite;
        partial void OnidSpecialiteChanging(global::System.String value);
        partial void OnidSpecialiteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 departement
        {
            get
            {
                return _departement;
            }
            set
            {
                OndepartementChanging(value);
                ReportPropertyChanging("departement");
                _departement = StructuralObject.SetValidValue(value, "departement");
                ReportPropertyChanged("departement");
                OndepartementChanged();
            }
        }
        private global::System.Int32 _departement;
        partial void OndepartementChanging(global::System.Int32 value);
        partial void OndepartementChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdlGSB", "rapport_fk2", "RAPPORT")]
        public EntityCollection<RAPPORT> RAPPORT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RAPPORT>("mdlGSB.rapport_fk2", "RAPPORT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RAPPORT>("mdlGSB.rapport_fk2", "RAPPORT", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdlGSB", Name="MEDICAMENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MEDICAMENT : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet MEDICAMENT.
        /// </summary>
        /// <param name="idMedicament">Valeur initiale de la propriété idMedicament.</param>
        /// <param name="nomCommercial">Valeur initiale de la propriété nomCommercial.</param>
        /// <param name="idFamille">Valeur initiale de la propriété idFamille.</param>
        /// <param name="composition">Valeur initiale de la propriété composition.</param>
        /// <param name="effets">Valeur initiale de la propriété effets.</param>
        /// <param name="contreIndications">Valeur initiale de la propriété contreIndications.</param>
        public static MEDICAMENT CreateMEDICAMENT(global::System.String idMedicament, global::System.String nomCommercial, global::System.String idFamille, global::System.String composition, global::System.String effets, global::System.String contreIndications)
        {
            MEDICAMENT mEDICAMENT = new MEDICAMENT();
            mEDICAMENT.idMedicament = idMedicament;
            mEDICAMENT.nomCommercial = nomCommercial;
            mEDICAMENT.idFamille = idFamille;
            mEDICAMENT.composition = composition;
            mEDICAMENT.effets = effets;
            mEDICAMENT.contreIndications = contreIndications;
            return mEDICAMENT;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idMedicament
        {
            get
            {
                return _idMedicament;
            }
            set
            {
                if (_idMedicament != value)
                {
                    OnidMedicamentChanging(value);
                    ReportPropertyChanging("idMedicament");
                    _idMedicament = StructuralObject.SetValidValue(value, false, "idMedicament");
                    ReportPropertyChanged("idMedicament");
                    OnidMedicamentChanged();
                }
            }
        }
        private global::System.String _idMedicament;
        partial void OnidMedicamentChanging(global::System.String value);
        partial void OnidMedicamentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomCommercial
        {
            get
            {
                return _nomCommercial;
            }
            set
            {
                OnnomCommercialChanging(value);
                ReportPropertyChanging("nomCommercial");
                _nomCommercial = StructuralObject.SetValidValue(value, false, "nomCommercial");
                ReportPropertyChanged("nomCommercial");
                OnnomCommercialChanged();
            }
        }
        private global::System.String _nomCommercial;
        partial void OnnomCommercialChanging(global::System.String value);
        partial void OnnomCommercialChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idFamille
        {
            get
            {
                return _idFamille;
            }
            set
            {
                OnidFamilleChanging(value);
                ReportPropertyChanging("idFamille");
                _idFamille = StructuralObject.SetValidValue(value, false, "idFamille");
                ReportPropertyChanged("idFamille");
                OnidFamilleChanged();
            }
        }
        private global::System.String _idFamille;
        partial void OnidFamilleChanging(global::System.String value);
        partial void OnidFamilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String composition
        {
            get
            {
                return _composition;
            }
            set
            {
                OncompositionChanging(value);
                ReportPropertyChanging("composition");
                _composition = StructuralObject.SetValidValue(value, false, "composition");
                ReportPropertyChanged("composition");
                OncompositionChanged();
            }
        }
        private global::System.String _composition;
        partial void OncompositionChanging(global::System.String value);
        partial void OncompositionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String effets
        {
            get
            {
                return _effets;
            }
            set
            {
                OneffetsChanging(value);
                ReportPropertyChanging("effets");
                _effets = StructuralObject.SetValidValue(value, false, "effets");
                ReportPropertyChanged("effets");
                OneffetsChanged();
            }
        }
        private global::System.String _effets;
        partial void OneffetsChanging(global::System.String value);
        partial void OneffetsChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contreIndications
        {
            get
            {
                return _contreIndications;
            }
            set
            {
                OncontreIndicationsChanging(value);
                ReportPropertyChanging("contreIndications");
                _contreIndications = StructuralObject.SetValidValue(value, false, "contreIndications");
                ReportPropertyChanged("contreIndications");
                OncontreIndicationsChanged();
            }
        }
        private global::System.String _contreIndications;
        partial void OncontreIndicationsChanging(global::System.String value);
        partial void OncontreIndicationsChanged();

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdlGSB", Name="RAPPORT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RAPPORT : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet RAPPORT.
        /// </summary>
        /// <param name="idRapport">Valeur initiale de la propriété idRapport.</param>
        /// <param name="idVisiteur">Valeur initiale de la propriété idVisiteur.</param>
        /// <param name="idMedecin">Valeur initiale de la propriété idMedecin.</param>
        public static RAPPORT CreateRAPPORT(global::System.Int32 idRapport, global::System.String idVisiteur, global::System.Int32 idMedecin)
        {
            RAPPORT rAPPORT = new RAPPORT();
            rAPPORT.idRapport = idRapport;
            rAPPORT.idVisiteur = idVisiteur;
            rAPPORT.idMedecin = idMedecin;
            return rAPPORT;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idRapport
        {
            get
            {
                return _idRapport;
            }
            set
            {
                if (_idRapport != value)
                {
                    OnidRapportChanging(value);
                    ReportPropertyChanging("idRapport");
                    _idRapport = StructuralObject.SetValidValue(value, "idRapport");
                    ReportPropertyChanged("idRapport");
                    OnidRapportChanged();
                }
            }
        }
        private global::System.Int32 _idRapport;
        partial void OnidRapportChanging(global::System.Int32 value);
        partial void OnidRapportChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dateRapport
        {
            get
            {
                return _dateRapport;
            }
            set
            {
                OndateRapportChanging(value);
                ReportPropertyChanging("dateRapport");
                _dateRapport = StructuralObject.SetValidValue(value, "dateRapport");
                ReportPropertyChanged("dateRapport");
                OndateRapportChanged();
            }
        }
        private Nullable<global::System.DateTime> _dateRapport;
        partial void OndateRapportChanging(Nullable<global::System.DateTime> value);
        partial void OndateRapportChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idMotif
        {
            get
            {
                return _idMotif;
            }
            set
            {
                OnidMotifChanging(value);
                ReportPropertyChanging("idMotif");
                _idMotif = StructuralObject.SetValidValue(value, "idMotif");
                ReportPropertyChanged("idMotif");
                OnidMotifChanged();
            }
        }
        private Nullable<global::System.Int32> _idMotif;
        partial void OnidMotifChanging(Nullable<global::System.Int32> value);
        partial void OnidMotifChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bilan
        {
            get
            {
                return _bilan;
            }
            set
            {
                OnbilanChanging(value);
                ReportPropertyChanging("bilan");
                _bilan = StructuralObject.SetValidValue(value, true, "bilan");
                ReportPropertyChanged("bilan");
                OnbilanChanged();
            }
        }
        private global::System.String _bilan;
        partial void OnbilanChanging(global::System.String value);
        partial void OnbilanChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idVisiteur
        {
            get
            {
                return _idVisiteur;
            }
            set
            {
                OnidVisiteurChanging(value);
                ReportPropertyChanging("idVisiteur");
                _idVisiteur = StructuralObject.SetValidValue(value, false, "idVisiteur");
                ReportPropertyChanged("idVisiteur");
                OnidVisiteurChanged();
            }
        }
        private global::System.String _idVisiteur;
        partial void OnidVisiteurChanging(global::System.String value);
        partial void OnidVisiteurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMedecin
        {
            get
            {
                return _idMedecin;
            }
            set
            {
                OnidMedecinChanging(value);
                ReportPropertyChanging("idMedecin");
                _idMedecin = StructuralObject.SetValidValue(value, "idMedecin");
                ReportPropertyChanged("idMedecin");
                OnidMedecinChanged();
            }
        }
        private global::System.Int32 _idMedecin;
        partial void OnidMedecinChanging(global::System.Int32 value);
        partial void OnidMedecinChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdlGSB", "rapport_fk2", "MEDECIN")]
        public MEDECIN MEDECIN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDECIN>("mdlGSB.rapport_fk2", "MEDECIN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDECIN>("mdlGSB.rapport_fk2", "MEDECIN").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MEDECIN> MEDECINReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDECIN>("mdlGSB.rapport_fk2", "MEDECIN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MEDECIN>("mdlGSB.rapport_fk2", "MEDECIN", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdlGSB", "rapport_fk1", "Visiteur")]
        public Visiteur Visiteur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Visiteur>("mdlGSB.rapport_fk1", "Visiteur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Visiteur>("mdlGSB.rapport_fk1", "Visiteur").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Visiteur> VisiteurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Visiteur>("mdlGSB.rapport_fk1", "Visiteur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Visiteur>("mdlGSB.rapport_fk1", "Visiteur", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdlGSB", Name="Visiteur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Visiteur : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Visiteur.
        /// </summary>
        /// <param name="idVisiteur">Valeur initiale de la propriété idVisiteur.</param>
        /// <param name="idLabo">Valeur initiale de la propriété idLabo.</param>
        /// <param name="identifiant">Valeur initiale de la propriété identifiant.</param>
        /// <param name="password">Valeur initiale de la propriété password.</param>
        public static Visiteur CreateVisiteur(global::System.String idVisiteur, global::System.Int32 idLabo, global::System.String identifiant, global::System.String password)
        {
            Visiteur visiteur = new Visiteur();
            visiteur.idVisiteur = idVisiteur;
            visiteur.idLabo = idLabo;
            visiteur.identifiant = identifiant;
            visiteur.password = password;
            return visiteur;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idVisiteur
        {
            get
            {
                return _idVisiteur;
            }
            set
            {
                if (_idVisiteur != value)
                {
                    OnidVisiteurChanging(value);
                    ReportPropertyChanging("idVisiteur");
                    _idVisiteur = StructuralObject.SetValidValue(value, false, "idVisiteur");
                    ReportPropertyChanged("idVisiteur");
                    OnidVisiteurChanged();
                }
            }
        }
        private global::System.String _idVisiteur;
        partial void OnidVisiteurChanging(global::System.String value);
        partial void OnidVisiteurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idLabo
        {
            get
            {
                return _idLabo;
            }
            set
            {
                OnidLaboChanging(value);
                ReportPropertyChanging("idLabo");
                _idLabo = StructuralObject.SetValidValue(value, "idLabo");
                ReportPropertyChanged("idLabo");
                OnidLaboChanged();
            }
        }
        private global::System.Int32 _idLabo;
        partial void OnidLaboChanging(global::System.Int32 value);
        partial void OnidLaboChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, true, "nom");
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, true, "prenom");
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rue
        {
            get
            {
                return _rue;
            }
            set
            {
                OnrueChanging(value);
                ReportPropertyChanging("rue");
                _rue = StructuralObject.SetValidValue(value, true, "rue");
                ReportPropertyChanged("rue");
                OnrueChanged();
            }
        }
        private global::System.String _rue;
        partial void OnrueChanging(global::System.String value);
        partial void OnrueChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cp
        {
            get
            {
                return _cp;
            }
            set
            {
                OncpChanging(value);
                ReportPropertyChanging("cp");
                _cp = StructuralObject.SetValidValue(value, true, "cp");
                ReportPropertyChanged("cp");
                OncpChanged();
            }
        }
        private global::System.String _cp;
        partial void OncpChanging(global::System.String value);
        partial void OncpChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ville
        {
            get
            {
                return _ville;
            }
            set
            {
                OnvilleChanging(value);
                ReportPropertyChanging("ville");
                _ville = StructuralObject.SetValidValue(value, true, "ville");
                ReportPropertyChanged("ville");
                OnvilleChanged();
            }
        }
        private global::System.String _ville;
        partial void OnvilleChanging(global::System.String value);
        partial void OnvilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dateEmbauche
        {
            get
            {
                return _dateEmbauche;
            }
            set
            {
                OndateEmbaucheChanging(value);
                ReportPropertyChanging("dateEmbauche");
                _dateEmbauche = StructuralObject.SetValidValue(value, true, "dateEmbauche");
                ReportPropertyChanged("dateEmbauche");
                OndateEmbaucheChanged();
            }
        }
        private global::System.String _dateEmbauche;
        partial void OndateEmbaucheChanging(global::System.String value);
        partial void OndateEmbaucheChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String identifiant
        {
            get
            {
                return _identifiant;
            }
            set
            {
                OnidentifiantChanging(value);
                ReportPropertyChanging("identifiant");
                _identifiant = StructuralObject.SetValidValue(value, false, "identifiant");
                ReportPropertyChanged("identifiant");
                OnidentifiantChanged();
            }
        }
        private global::System.String _identifiant;
        partial void OnidentifiantChanging(global::System.String value);
        partial void OnidentifiantChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdlGSB", "rapport_fk1", "RAPPORT")]
        public EntityCollection<RAPPORT> RAPPORT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RAPPORT>("mdlGSB.rapport_fk1", "RAPPORT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RAPPORT>("mdlGSB.rapport_fk1", "RAPPORT", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
